package cn.sqyl.dao;

import cn.sqyl.dataobject.classevent;

import java.util.List;

public interface classeventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int insert(classevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int insertSelective(classevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    classevent selectByPrimaryKey(Integer id);
    List<classevent> selectByUserId(Integer belong_userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int updateByPrimaryKeySelective(classevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int updateByPrimaryKey(classevent record);
}