package cn.sqyl.dao;

import cn.sqyl.dataobject.classevent;
import cn.sqyl.dataobject.dakaevent;

import java.util.List;

public interface dakaeventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dakaevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dakaevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int insert(dakaevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dakaevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int insertSelective(dakaevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dakaevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    dakaevent selectByPrimaryKey(Integer id);
    List<dakaevent> selectByUserId(Integer belong_userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dakaevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int updateByPrimaryKeySelective(dakaevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dakaevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(dakaevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dakaevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int updateByPrimaryKey(dakaevent record);
}