package cn.sqyl.dao;

import cn.sqyl.dataobject.classevent;
import cn.sqyl.dataobject.daka_msg;
import cn.sqyl.dataobject.daka_msgKey;

import java.util.List;

public interface daka_msgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daka_msg
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int deleteByPrimaryKey(daka_msgKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daka_msg
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int insert(daka_msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daka_msg
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int insertSelective(daka_msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daka_msg
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    daka_msg selectByPrimaryKey(daka_msgKey key);
    List<daka_msg> selectByDakaId(Integer belong_dakaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daka_msg
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int updateByPrimaryKeySelective(daka_msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daka_msg
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(daka_msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daka_msg
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int updateByPrimaryKey(daka_msg record);
}