package cn.sqyl.dao;

import cn.sqyl.dataobject.dayevent;

import java.util.List;

public interface dayeventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dayevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dayevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int insert(dayevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dayevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int insertSelective(dayevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dayevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    dayevent selectByPrimaryKey(Integer id);
    List<dayevent> selectByUserId(Integer belong_userid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dayevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int updateByPrimaryKeySelective(dayevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dayevent
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int updateByPrimaryKey(dayevent record);
}