package cn.sqyl.dao;

import cn.sqyl.dataobject.friends;

import java.util.List;

public interface friendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int insert(friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int insertSelective(friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    List<friends> selectByUserId(Integer belong_UserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int updateByPrimaryKeySelective(friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    int updateByPrimaryKey(friends record);
}