package cn.sqyl.dataobject;

public class classevent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classevent.id
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classevent.name
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classevent.belong_UserID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private Integer belongUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classevent.class_date
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private Integer classDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classevent.begin_class
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private Integer beginClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classevent.end_class
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private Integer endClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classevent.teacher
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private String teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classevent.classroom
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private String classroom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classevent.id
     *
     * @return the value of classevent.id
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classevent.id
     *
     * @param id the value for classevent.id
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classevent.name
     *
     * @return the value of classevent.name
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classevent.name
     *
     * @param name the value for classevent.name
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classevent.belong_UserID
     *
     * @return the value of classevent.belong_UserID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public Integer getBelongUserid() {
        return belongUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classevent.belong_UserID
     *
     * @param belongUserid the value for classevent.belong_UserID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setBelongUserid(Integer belongUserid) {
        this.belongUserid = belongUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classevent.class_date
     *
     * @return the value of classevent.class_date
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public Integer getClassDate() {
        return classDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classevent.class_date
     *
     * @param classDate the value for classevent.class_date
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setClassDate(Integer classDate) {
        this.classDate = classDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classevent.begin_class
     *
     * @return the value of classevent.begin_class
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public Integer getBeginClass() {
        return beginClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classevent.begin_class
     *
     * @param beginClass the value for classevent.begin_class
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setBeginClass(Integer beginClass) {
        this.beginClass = beginClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classevent.end_class
     *
     * @return the value of classevent.end_class
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public Integer getEndClass() {
        return endClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classevent.end_class
     *
     * @param endClass the value for classevent.end_class
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setEndClass(Integer endClass) {
        this.endClass = endClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classevent.teacher
     *
     * @return the value of classevent.teacher
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classevent.teacher
     *
     * @param teacher the value for classevent.teacher
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classevent.classroom
     *
     * @return the value of classevent.classroom
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public String getClassroom() {
        return classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classevent.classroom
     *
     * @param classroom the value for classevent.classroom
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setClassroom(String classroom) {
        this.classroom = classroom == null ? null : classroom.trim();
    }
}