package cn.sqyl.dataobject;

public class daka_msg extends daka_msgKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daka_msg.time
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daka_msg.comment
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daka_msg.time
     *
     * @return the value of daka_msg.time
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daka_msg.time
     *
     * @param time the value for daka_msg.time
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daka_msg.comment
     *
     * @return the value of daka_msg.comment
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daka_msg.comment
     *
     * @param comment the value for daka_msg.comment
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}