package cn.sqyl.dataobject;

public class dayevent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dayevent.id
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dayevent.name
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dayevent.belong_UserID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private Integer belongUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dayevent.time
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dayevent.date
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dayevent.id
     *
     * @return the value of dayevent.id
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dayevent.id
     *
     * @param id the value for dayevent.id
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dayevent.name
     *
     * @return the value of dayevent.name
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dayevent.name
     *
     * @param name the value for dayevent.name
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dayevent.belong_UserID
     *
     * @return the value of dayevent.belong_UserID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public Integer getBelongUserid() {
        return belongUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dayevent.belong_UserID
     *
     * @param belongUserid the value for dayevent.belong_UserID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setBelongUserid(Integer belongUserid) {
        this.belongUserid = belongUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dayevent.time
     *
     * @return the value of dayevent.time
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dayevent.time
     *
     * @param time the value for dayevent.time
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dayevent.date
     *
     * @return the value of dayevent.date
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dayevent.date
     *
     * @param date the value for dayevent.date
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }
}