package cn.sqyl.dataobject;

public class friends {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.id
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.belong_UserID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private Integer belongUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friendID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private Integer friendid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.id
     *
     * @return the value of friends.id
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.id
     *
     * @param id the value for friends.id
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.belong_UserID
     *
     * @return the value of friends.belong_UserID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public Integer getBelongUserid() {
        return belongUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.belong_UserID
     *
     * @param belongUserid the value for friends.belong_UserID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setBelongUserid(Integer belongUserid) {
        this.belongUserid = belongUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friendID
     *
     * @return the value of friends.friendID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public Integer getFriendid() {
        return friendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friendID
     *
     * @param friendid the value for friends.friendID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setFriendid(Integer friendid) {
        this.friendid = friendid;
    }
}