package cn.sqyl.dataobject;

public class userclass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userclass.userID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userclass.userAccount
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private String useraccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userclass.userName
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userclass.userID
     *
     * @return the value of userclass.userID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userclass.userID
     *
     * @param userid the value for userclass.userID
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userclass.userAccount
     *
     * @return the value of userclass.userAccount
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public String getUseraccount() {
        return useraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userclass.userAccount
     *
     * @param useraccount the value for userclass.userAccount
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setUseraccount(String useraccount) {
        this.useraccount = useraccount == null ? null : useraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userclass.userName
     *
     * @return the value of userclass.userName
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userclass.userName
     *
     * @param username the value for userclass.userName
     *
     * @mbg.generated Mon May 10 21:11:49 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}